[Fix] #9 - gradle.yml 수정

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -22,18 +22,7 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      # 2. Spring Boot Applications Build
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
-
-      - name: permission for gradlew
-        run: chmod +x ./gradlew
-        shell: bash
-
-      - name : Build with Gradle Wrapper
-        run : ./gradlew build --stacktrace --info
-
-      #3. YML File Build
+      #2. YML File Build
       - name: Set jwt YML
         run: |
           touch ./src/main/resources/application-jwt.yml
@@ -49,6 +38,27 @@ jobs:
           touch ./src/main/resources/application-real.yml
           echo "${{secrets.APPLICATION_REAL_YML}}" | base64 --decode > src/main/resources/application-real.yml
 
+      - name: Check if YML files exist
+        run: |
+          if [ -f ./src/main/resources/application-jwt.yml ] && \
+             [ -f ./src/main/resources/application-codef.yml ] && \
+             [ -f ./src/main/resources/application-real.yml ]; then
+            echo "YML files exist."
+          else
+            echo "One or more YML files are missing."
+            exit 1
+          fi
+
+      # 3. Spring Boot Applications Build
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
+
+      - name: permission for gradlew
+        run: chmod +x ./gradlew
+        shell: bash
+
+      - name : Build with Gradle Wrapper
+        run : ./gradlew build --stacktrace --info
 
       # 4. 빌드 결과 확인
       - name: Verify build
